const arr =[
  {
    "nome": "Ana Silva",
    "idade": 19,
    "email": "anauser1@gmail.com",
    "gostos": ["Dança", "Música", "Cozinhar"],
    "urlFotos": ["1763520000001_foto1.png", "1763520000002_foto2.png"],
    "cidade": "Recife",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Sou Ana, adoro dançar e conhecer pessoas novas.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Esteticista",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Bruna Costa",
    "idade": 20,
    "email": "brunauser2@gmail.com",
    "gostos": ["Musculação", "TikTok", "Viajar"],
    "urlFotos": ["1763520001001_foto1.png", "1763520001002_foto2.png"],
    "cidade": "São Paulo",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Bruna aqui! Amo treinar e viajar sempre que posso.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Designer Gráfico",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Carolina Mendes",
    "idade": 21,
    "email": "caroluser3@gmail.com",
    "gostos": ["Fotografia", "Ciclismo", "Filmes"],
    "urlFotos": ["1763520002001_foto1.png", "1763520002002_foto2.png"],
    "cidade": "Curitiba",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Gosto de aventuras, fotos e bons filmes.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Publicitária",
    "educacao": "Ensino superior incompleto",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Daniela Rocha",
    "idade": 22,
    "email": "daniuser4@gmail.com",
    "gostos": ["Yoga", "Leitura", "Café"],
    "urlFotos": ["1763520003001_foto1.png", "1763520003002_foto2.png"],
    "cidade": "Belo Horizonte",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Sou calma, adoro livros e dias tranquilos.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Assistente Administrativo",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Eduarda Lima",
    "idade": 18,
    "email": "eduardauser5@gmail.com",
    "gostos": ["Séries", "Make", "Moda"],
    "urlFotos": ["1763520004001_foto1.png", "1763520004002_foto2.png"],
    "cidade": "Campina Grande",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Sou Eduarda, amante de séries e maquiagem.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Designer de Sobrancelhas",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Fernanda Oliveira",
    "idade": 23,
    "email": "fernandauser6@gmail.com",
    "gostos": ["Corrida", "Cozinhar", "Fotografia"],
    "urlFotos": ["1763520005001_foto1.png", "1763520005002_foto2.png"],
    "cidade": "Porto Alegre",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Gosto de treinar e cozinhar pratos diferentes.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Nutricionista",
    "educacao": "Ensino superior completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Gabriela Torres",
    "idade": 20,
    "email": "gabiuser7@gmail.com",
    "gostos": ["TikTok", "Viagens", "Surf"],
    "urlFotos": ["1763520006001_foto1.png", "1763520006002_foto2.png"],
    "cidade": "Florianópolis",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Amo praia, viagens e criar conteúdo.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Social Media",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Helena Duarte",
    "idade": 22,
    "email": "helenauser8@gmail.com",
    "gostos": ["Arte", "Pintura", "Música"],
    "urlFotos": ["1763520007001_foto1.png", "1763520007002_foto2.png"],
    "cidade": "Salvador",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Criativa, sonhadora e apaixonada por arte.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Artista Plástico",
    "educacao": "Ensino superior incompleto",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Isabela Freitas",
    "idade": 19,
    "email": "isabelauser9@gmail.com",
    "gostos": ["Leitura", "Séries", "Caminhada"],
    "urlFotos": ["1763520008001_foto1.png", "1763520008002_foto2.png"],
    "cidade": "Rio de Janeiro",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Amo livros, praia e boas conversas.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Assistente de Marketing",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  },
  {
    "nome": "Julia Ribeiro",
    "idade": 20,
    "email": "juliauser10@gmail.com",
    "gostos": ["Academia", "Moda", "Música"],
    "urlFotos": ["1763520009001_foto1.png", "1763520009002_foto2.png"],
    "cidade": "Fortaleza",
    "genero": "feminino",
    "sexualidade": "heterossexual",
    "toProcurando": "homem",
    "bio": "Julia aqui! Amo treinar e me vestir bem.",
    "cidadesExibicao": ["todas"],
    "ocupacao": "Vendedora",
    "educacao": "Ensino médio completo",
    "_class": "com.example.demo.modules.usuarios.User"
  }
]

async function cadastrar(params) {
    await fetch(`http://localhost:8080/User/createUser`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(params)
    })
}
(async () => {
    await Promise.all(arr.map(cadastrar));
    console.log("Todos os usuários cadastrados!");
})();