const arr = [
    {
        "nome": "Lucas Andrade",
        "email": "lucas.andrade@example.com",
        "gostos": ["Musculação", "Ciclismo", "Futebol", "Tecnologia", "Streaming"],
        "urlFotos": ["https://images.unsplash.com/photo-1603415526960-f7e0328b92b2"],
        "cidade": "São Paulo",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Apaixonado por tecnologia e esportes. Sempre buscando evolução pessoal e profissional.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Desenvolvedor Web",
        "educacao": "Engenharia de Software - USP",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Mariana Silva",
        "email": "mariana.silva@example.com",
        "gostos": ["Dança", "Cinema", "Fotografia", "Ler livros", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        "cidade": "Rio de Janeiro",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Fotógrafa nas horas vagas, fã de cinema independente e viagens culturais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Fotógrafa",
        "educacao": "Curso técnico em Fotografia",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Pedro Costa",
        "email": "pedro.costa@example.com",
        "gostos": ["Futebol", "Jogar videogame", "Cozinhar", "Musculação", "Cervejas artesanais"],
        "urlFotos": ["https://images.unsplash.com/photo-1544005313-94ddf0286df2"],
        "cidade": "Campina Grande",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "qualquer um",
        "bio": "Dev que cozinha nas horas vagas. Gosto de treinar e de um bom churrasco com amigos.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Programador",
        "educacao": "Análise e Desenvolvimento de Sistemas",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Ana Beatriz",
        "email": "ana.beatriz@example.com",
        "gostos": ["Yoga", "Meditação", "Cozinhar", "Leitura", "Viajar"],
        "urlFotos": ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"],
        "cidade": "Salvador",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Instrutora de yoga, amante de livros e viagens sustentáveis.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Instrutora de Yoga",
        "educacao": "Licenciatura em Educação Física",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Rafael Gomes",
        "email": "rafael.gomes@example.com",
        "gostos": ["Música", "Tocar violão", "Cinema", "Corrida", "Ciclismo"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Belo Horizonte",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Músico amador, corre nas manhãs de sábado e curte cinema nacional.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Analista de Sistemas",
        "educacao": "Ciência da Computação",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Beatriz Souza",
        "email": "beatriz.souza@example.com",
        "gostos": ["Fotografia", "Moda", "Design gráfico", "Pintura", "Café"],
        "urlFotos": ["https://images.unsplash.com/photo-1545996124-4b0b7b3b3a6b"],
        "cidade": "Florianópolis",
        "genero": "feminino",
        "sexualidade": "bissexual",
        "toProcurando": "amizades",
        "bio": "Designer gráfica que ama retratar paisagens e pessoas pela lente.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Designer Gráfico",
        "educacao": "Design Gráfico - Universidade Federal",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Gabriel Pereira",
        "email": "gabriel.pereira@example.com",
        "gostos": ["Programação", "IA", "Jogos de tabuleiro", "Café", "Trilhas"],
        "urlFotos": ["https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"],
        "cidade": "Brasília",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Engenheiro de software interessado em IA e jogos estratégicos.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Engenheiro de Software",
        "educacao": "Engenharia de Software",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Carolina Lopes",
        "email": "carolina.lopes@example.com",
        "gostos": ["Cozinhar", "Viajar", "Fotografia", "Pilates", "Ler livros"],
        "urlFotos": ["https://images.unsplash.com/photo-1517841905240-472988babdf9"],
        "cidade": "Fortaleza",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Amante de gastronomia e de roteiros de viagem pouco convencionais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Gastronomia",
        "educacao": "Culinária Profissional",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Mateus Ribeiro",
        "email": "mateus.ribeiro@example.com",
        "gostos": ["Futebol", "Skate", "Música", "Cervejas artesanais", "Tecnologia"],
        "urlFotos": ["https://images.unsplash.com/photo-1531123414780-fb42c8d36f27"],
        "cidade": "Curitiba",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Skatista urbano, curioso por tecnologia e música indie.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "DevOps Engineer",
        "educacao": "Sistemas para Internet",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Helena Martins",
        "email": "helena.martins@example.com",
        "gostos": ["Leitura", "Escrita criativa", "Poesia", "Cafés", "Museus"],
        "urlFotos": ["https://images.unsplash.com/photo-1494790108377-be9c29b29330"],
        "cidade": "Recife",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Escritora em formação, sempre com um livro novo na bolsa.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Redatora",
        "educacao": "Letras",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Tiago Carvalho",
        "email": "tiago.carvalho@example.com",
        "gostos": ["Natação", "Ciclismo", "Música", "Desenvolvimento de jogos", "Culinária"],
        "urlFotos": ["https://images.unsplash.com/photo-1542060744-6e9f3b9d7a2d"],
        "cidade": "Manaus",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "qualquer um",
        "bio": "Game dev nas horas vagas, gosto de treinar e explorar a culinária local.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Desenvolvedor de Jogos",
        "educacao": "Desenvolvimento de Jogos - Curso técnico",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Larissa Fernandes",
        "email": "larissa.fernandes@example.com",
        "gostos": ["Teatro", "Cinema", "Dança", "Fotografia", "Artesanato"],
        "urlFotos": ["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"],
        "cidade": "Juiz de Fora",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Atriz amadora, adoro projetos culturais e oficinas de teatro.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Ator",
        "educacao": "Curso de Teatro",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Diego Santos",
        "email": "diego.santos@example.com",
        "gostos": ["Automobilismo", "Futebol", "Tecnologia", "Startups", "Café"],
        "urlFotos": ["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"],
        "cidade": "Goiânia",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Empreendedor no setor de mobilidade, sempre buscando novas conexões.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Product Manager",
        "educacao": "Administração",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Júlia Almeida",
        "email": "julia.almeida@example.com",
        "gostos": ["Moda", "Design", "Fotografia", "Makeup", "Yoga"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Vitória",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Stylist e entusiasta de moda sustentável.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Stylist",
        "educacao": "Design de Moda",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "André Lima",
        "email": "andre.lima@example.com",
        "gostos": ["Musculação", "Crossfit", "Nutrição", "Tecnologia", "Podcasts"],
        "urlFotos": ["https://images.unsplash.com/photo-1570295999919-56ceb5ecca61"],
        "cidade": "Campo Grande",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "treino parceiro",
        "bio": "Personal trainer e entusiasta de performance.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Personal Trainer",
        "educacao": "Educação Física",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Sofia Rodrigues",
        "email": "sofia.rodrigues@example.com",
        "gostos": ["Viagens", "Ler", "Fotografia", "Jornalismo", "Música"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Natal",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Jornalista em formação, apaixonada por culturas locais e viagens.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Jornalista",
        "educacao": "Comunicação Social - Jornalismo",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Marcos Vinicius",
        "email": "marcos.vinicius@example.com",
        "gostos": ["Pesca esportiva", "Trilhas", "Fotografia", "Música", "Cerveja"],
        "urlFotos": ["https://images.unsplash.com/photo-1502767089025-6572583495b0"],
        "cidade": "Boa Vista",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "qualquer um",
        "bio": "Explorador de natureza, sempre com equipamento fotográfico na mochila.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Guia de Ecoturismo",
        "educacao": "Turismo",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Patrícia Nunes",
        "email": "patricia.nunes@example.com",
        "gostos": ["Culinária", "Panificação", "Cafés", "Leitura", "Artes"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Maceió",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Chef amadora, especializada em pães artesanais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Chef",
        "educacao": "Gastronomia",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Vitor Matos",
        "email": "vitor.matos@example.com",
        "gostos": ["Esportes", "Tênis", "Corrida", "Tecnologia", "Games"],
        "urlFotos": ["https://images.unsplash.com/photo-1485217988980-11786ced9454"],
        "cidade": "Anápolis",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "treino parceiro",
        "bio": "Atleta amador, procura parceiros de treino e jogos de fim de semana.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Analista de BI",
        "educacao": "Administração com ênfase em TI",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Isabela Farias",
        "email": "isabela.farias@example.com",
        "gostos": ["Pintura", "Artesanato", "Yoga", "Música", "Design"],
        "urlFotos": ["https://images.unsplash.com/photo-1517841905240-472988babdf9"],
        "cidade": "Palmas",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Artista plástica e instrutora de oficinas manuais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Artista Plástica",
        "educacao": "Belas Artes",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Fábio Oliveira",
        "email": "fabio.oliveira@example.com",
        "gostos": ["Pesca esportiva", "Caminhadas", "Fotografia", "Música", "Tecnologia"],
        "urlFotos": ["https://images.unsplash.com/photo-1502767089025-6572583495b0"],
        "cidade": "Porto Velho",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "aventura",
        "bio": "Aventureiro nas horas vagas, adoro registrar paisagens remotas.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Guia",
        "educacao": "Turismo e Hotelaria",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Camila Rocha",
        "email": "camila.rocha@example.com",
        "gostos": ["Canto", "Música", "Dança", "Viagens", "Cinema"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Niterói",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Cantora amadora e bailarina, adoro apresentações locais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Cantora",
        "educacao": "Cursos de Técnica Vocal",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Rogério Alves",
        "email": "rogerio.alves@example.com",
        "gostos": ["Carros", "Automobilismo", "Futebol", "Tecnologia", "Cerveja"],
        "urlFotos": ["https://images.unsplash.com/photo-1544005313-94ddf0286df2"],
        "cidade": "Porto Alegre",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "qualquer um",
        "bio": "Engenheiro mecânico e entusiasta de automobilismo.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Engenheiro Mecânico",
        "educacao": "Engenharia Mecânica",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Olívia Pereira",
        "email": "olivia.pereira@example.com",
        "gostos": ["Moda", "Fotografia", "Cozinhar", "Leitura", "Viajar"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Santos",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Influencer de lifestyle e apaixonada por viagens costeiras.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Criadora de Conteúdo",
        "educacao": "Comunicação Social",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Eduardo Fernandes",
        "email": "eduardo.fernandes@example.com",
        "gostos": ["Programação", "Data Science", "Café", "Ler", "Jogos de tabuleiro"],
        "urlFotos": ["https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"],
        "cidade": "Cuiabá",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Cientista de dados, gosto de extrair histórias dos dados e de café forte.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Cientista de Dados",
        "educacao": "Ciência de Dados",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Natália Pinto",
        "email": "natalia.pinto@example.com",
        "gostos": ["Teatro", "Cinema", "Escrita criativa", "Poesia", "Café"],
        "urlFotos": ["https://images.unsplash.com/photo-1494790108377-be9c29b29330"],
        "cidade": "Aracaju",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Roteirista e amante de poesias urbanas.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Roteirista",
        "educacao": "Comunicação e Artes",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Bruno Rocha",
        "email": "bruno.rocha@example.com",
        "gostos": ["Boxe", "Muay Thai", "Musculação", "Corrida", "Tecnologia"],
        "urlFotos": ["https://images.unsplash.com/photo-1570295999919-56ceb5ecca61"],
        "cidade": "Dourados",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "treino parceiro",
        "bio": "Atleta de lutas e instrutor, apaixonado por performance.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Instrutor de Luta",
        "educacao": "Educação Física",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Amanda Vieira",
        "email": "amanda.vieira@example.com",
        "gostos": ["Moda", "Design", "Makeup", "Fotografia", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        "cidade": "Joinville",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Designer e entusiasta por tendências de moda e estética.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "UI Designer",
        "educacao": "Design de Interfaces",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Henrique Castro",
        "email": "henrique.castro@example.com",
        "gostos": ["Tecnologia", "Montagem de PCs", "Segurança digital", "Cafés", "Jogos"],
        "urlFotos": ["https://images.unsplash.com/photo-1544005313-94ddf0286df2"],
        "cidade": "Rondonópolis",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Técnico em redes, interessado em segurança e hardware.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Administrador de Redes",
        "educacao": "Técnico em Informática",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Bianca Moura",
        "email": "bianca.moura@example.com",
        "gostos": ["Culinária", "Comida fitness", "Yoga", "Leitura", "Música"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Teresina",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Nutricionista focada em alimentação saudável e bem-estar.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Nutricionista",
        "educacao": "Nutrição",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Gustavo Almeida",
        "email": "gustavo.almeida@example.com",
        "gostos": ["Blockchain", "Criptomoedas", "Programação", "Leitura", "Café"],
        "urlFotos": ["https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"],
        "cidade": "São Luís",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Entusiasta de blockchain e desenvolvedor backend.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Especialista em Blockchain",
        "educacao": "Engenharia de Computação",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Laura Cardoso",
        "email": "laura.cardoso@example.com",
        "gostos": ["Dança", "Teatro", "Cinema", "Leitura", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Olinda",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Atriz e bailarina que adora projetos culturais locais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Atriz",
        "educacao": "Artes cênicas",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Rafael Nogueira",
        "email": "rafael.nogueira@example.com",
        "gostos": ["Fotografia", "Viajar", "Mergulho", "Trilhas", "Surf"],
        "urlFotos": ["https://images.unsplash.com/photo-1502767089025-6572583495b0"],
        "cidade": "Parintins",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "aventura",
        "bio": "Guia de expedições e fotógrafo de natureza.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Guia de Expedições",
        "educacao": "Turismo",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Sabrina Melo",
        "email": "sabrina.melo@example.com",
        "gostos": ["Yoga", "Meditação", "Pilates", "Leitura", "Culinária"],
        "urlFotos": ["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        "cidade": "Araguaína",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Instrutora de Pilates, amante de bem-estar holístico.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Instrutora de Pilates",
        "educacao": "Educação Física",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Leandro Silva",
        "email": "leandro.silva@example.com",
        "gostos": ["Programação", "DevOps", "Música", "Futebol", "Cerveja"],
        "urlFotos": ["https://images.unsplash.com/photo-1567427018141-0584cfcbf1a3"],
        "cidade": "Ananindeua",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "SRE focado em escalabilidade e automação.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "SRE",
        "educacao": "Engenharia de Software",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Fernanda Lopes",
        "email": "fernanda.lopes@example.com",
        "gostos": ["Artesanato", "Design", "Leitura", "Café", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Imperatriz",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Designer e craft lover, faço oficinas locais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Designer de Produto",
        "educacao": "Design Industrial",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Maurício Barros",
        "email": "mauricio.barros@example.com",
        "gostos": ["Golfe", "Tênis", "Ler", "Vinhos", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1485217988980-11786ced9454"],
        "cidade": "Juazeiro do Norte",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Executivo que gosta de esportes e viagens internacionais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Gestor Comercial",
        "educacao": "Administração",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Camilo Santana",
        "email": "camilo.santana@example.com",
        "gostos": ["Ciclismo", "Trilhas", "Fotografia", "Camping", "Música"],
        "urlFotos": ["https://images.unsplash.com/photo-1503416997304-8d4b6a5d0e1b"],
        "cidade": "Teresina",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "aventura",
        "bio": "Apaixonado por atividades ao ar livre e fotografia de paisagem.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Guia de Trilhas",
        "educacao": "Licenciatura em Geografia",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Rita Alves",
        "email": "rita.alves@example.com",
        "gostos": ["Pilates", "Yoga", "Nutrição", "Leitura", "Cozinhar"],
        "urlFotos": ["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        "cidade": "Mossoró",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Profissional de saúde preocupada com qualidade de vida.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Nutricionista",
        "educacao": "Nutrição",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Alexandre Pinto",
        "email": "alexandre.pinto@example.com",
        "gostos": ["Desenvolvimento web", "Front-end", "UI/UX", "Café", "Startups"],
        "urlFotos": ["https://images.unsplash.com/photo-1542060744-6e9f3b9d7a2d"],
        "cidade": "Campinas",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Fullstack developer interessado em produtos digitais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Full Stack Developer",
        "educacao": "Engenharia de Software",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Priscila Duarte",
        "email": "priscila.duarte@example.com",
        "gostos": ["Cozinhar", "Leitura", "Viajar", "Cinema", "Artes"],
        "urlFotos": ["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"],
        "cidade": "Caruaru",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Cozinheira e pesquisadora de receitas regionais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Chef de Cozinha",
        "educacao": "Gastronomia",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Samuel Ribeiro",
        "email": "samuel.ribeiro@example.com",
        "gostos": ["Tocar guitarra", "Música", "Produção musical", "Cerveja", "Futebol"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Juazeiro do Norte",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Músico e produtor independente, toco em bandas locais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Produtor Musical",
        "educacao": "Produção Musical",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Verônica Ramos",
        "email": "veronica.ramos@example.com",
        "gostos": ["Voluntariado", "Ações ambientais", "Leitura", "Café", "Caminhadas"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Pelotas",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "projetos sociais",
        "bio": "Trabalhadora em ONGs ambientais, busco colaborar em projetos locais.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Coordenadora de Projetos Sociais",
        "educacao": "Serviço Social",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Filipe Nascimento",
        "email": "filipe.nascimento@example.com",
        "gostos": ["Skate", "Surf", "Fotografia", "Música", "Viagens"],
        "urlFotos": ["https://images.unsplash.com/photo-1503416997304-8d4b6a5d0e1b"],
        "cidade": "Blumenau",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "aventura",
        "bio": "Apreciador de esportes urbanos e de praia, sempre com câmera à mão.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Fotógrafo",
        "educacao": "Curso técnico em Fotografia",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Monica Teixeira",
        "email": "monica.teixeira@example.com",
        "gostos": ["Dança fitness", "Yoga", "Nutrição", "Artes", "Leitura"],
        "urlFotos": ["https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        "cidade": "Nacional",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "amizades",
        "bio": "Instrutora de dança fitness e entusiasta de bem-estar.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Instrutora de Dança",
        "educacao": "Educação Física",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Cláudio Menezes",
        "email": "claudio.menezes@example.com",
        "gostos": ["Ciclismo", "Carros", "Tecnologia", "Startups", "Corrida"],
        "urlFotos": ["https://images.unsplash.com/photo-1567427018141-0584cfcbf1a3"],
        "cidade": "Londrina",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "qualquer um",
        "bio": "Empreendedor tech e amante de pedaladas ao ar livre.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Empreendedor",
        "educacao": "Administração",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Paula Mendes",
        "email": "paula.mendes@example.com",
        "gostos": ["Leitura", "Maratona", "Pilates", "Cozinhar", "Jardinagem"],
        "urlFotos": ["https://images.unsplash.com/photo-1502685104226-ee32379fefbe"],
        "cidade": "Caxias do Sul",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "treino parceiro",
        "bio": "Corredora e amante de plantas, sempre com uma receita saudável na manga.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Engenheira Ambiental",
        "educacao": "Engenharia Ambiental",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Rodrigo Duarte",
        "email": "rodrigo.duarte@example.com",
        "gostos": ["Programação", "DevOps", "Cerveja artesanal", "Games", "Música"],
        "urlFotos": ["https://images.unsplash.com/photo-1542060744-6e9f3b9d7a2d"],
        "cidade": "Sinop",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "networking",
        "bio": "Desenvolvedor backend que curte abrir um projeto open-source.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Backend Developer",
        "educacao": "Sistemas de Informação",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Daniela Costa",
        "email": "daniela.costa@example.com",
        "gostos": ["Moda", "Maquiagem artística", "Fotografia", "Dança", "Música"],
        "urlFotos": ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
        "cidade": "Serra",
        "genero": "feminino",
        "sexualidade": "heterossexual",
        "toProcurando": "relacionamento",
        "bio": "Makeup artist freelance, adoro ensaios criativos.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Maquiadora",
        "educacao": "Cursos técnicos de maquiagem",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    },
    {
        "nome": "Igor Fonseca",
        "email": "igor.fonseca@example.com",
        "gostos": ["E-sports", "Streaming", "Games", "Tecnologia", "Café"],
        "urlFotos": ["https://images.unsplash.com/photo-1567427018141-0584cfcbf1a3"],
        "cidade": "Uberlândia",
        "genero": "masculino",
        "sexualidade": "heterossexual",
        "toProcurando": "jogar junto",
        "bio": "Streamer e jogador competitivo, sempre atrás do próximo ranking.",
        "cidadesExibicao": ["todas"],
        "ocupacao": "Streamer",
        "educacao": "Curso de Produção de Conteúdo",
        "planoStatus": null,
        "perfisVisualizados": [],
        "_class": "com.example.demo.modules.usuarios.User"
    }
]
async function cadastrar(params) {
    await fetch(`http://localhost:8080/User/createUser`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(params)
    })
}
(async () => {
    await Promise.all(arr.map(cadastrar));
    console.log("Todos os usuários cadastrados!");
})();